name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Job 1: Pruebas automatizadas
  test:
    name: Pruebas Automatizadas
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar tests unitarios
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Generar reporte de cobertura
        run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless

      - name: Subir reporte de cobertura
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: false

  # Job 2: Escaneo de vulnerabilidades
  security:
    name: Escaneo de Seguridad
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Auditoría de dependencias (npm audit)
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Escaneo con Snyk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Análisis de código estático con SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Escaneo de secretos con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Subir resultados a GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  # Job 3: Construcción de la aplicación
  build:
    name: Construcción de la App
    runs-on: ubuntu-latest
    needs: [test, security]
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Build de producción
        run: npm run build -- --configuration production

      - name: Comprimir artefactos
        run: tar -czf dist.tar.gz dist/

      - name: Guardar artefactos del build
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist.tar.gz
          retention-days: 7

  # Job 4: Despliegue en entorno de pruebas
  deploy-staging:
    name: Despliegue a Staging
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: staging
      url: https://staging.tu-dominio.com
    
    steps:
      - name: Descargar artefactos
        uses: actions/download-artifact@v4
        with:
          name: angular-build

      - name: Descomprimir build
        run: tar -xzf dist.tar.gz

      # Opción 1: Despliegue a GitHub Pages
      - name: Deploy a GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/tu-app-name/browser
          cname: staging.tu-dominio.com

      # Opción 2: Despliegue a Netlify
      - name: Deploy a Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./dist/tu-app-name/browser
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy desde GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # Opción 3: Despliegue a servidor via SSH
      - name: Deploy via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/staging"

      # Opción 4: Despliegue a AWS S3
      - name: Deploy a AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'dist/tu-app-name/browser'

      - name: Notificar éxito del deploy
        if: success()
        run: |
          echo "Deploy exitoso a staging!"
          echo "URL: https://staging.tu-dominio.com"

      - name: Notificar fallo del deploy
        if: failure()
        run: echo "El deploy a staging falló"

  # Job 5: Notificaciones
  notify:
    name: Notificaciones
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    if: always()
    
    steps:
      - name: Enviar notificación de resultado
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          text: |
            Pipeline completado
            Resultado: ${{ job.status }}
            Rama: ${{ github.ref }}
            Commit: ${{ github.sha }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}